### PR TITLE
Authorization Issue

### PR DESCRIPTION
**Pull request by captainnilo**
Hi,

we fixed the authorization of the client API and use "Basic Auth" now. This fixed 401 request coming back from tutum Rest-API.

### CODE REVIEW

**Comment by jeromebridge** [comment]
Is this an alternative header to `ApiKey` that can be used to authenticate?

**Comment by captainnilo** [comment]
Actually this is the only allowed header for authorization according to tutum:
https://docs.tutum.co/v2/api/#rest-api

I received 401 with the apikeys header set.

**Comment by jeromebridge** [comment]
You are right...I wonder if that is recent?  I'm testing my app that I use just to verify as well.  If that fails I'll just merge your changes as they are.

Weird that my app still works, but the documentation clearly says to use Basic so I'll just take your change.

**Comment by jeromebridge** [comment]
I believe I merged your changes with my last commit.

**Pull request closed without merging**
